spring:
  application:
    name: Arcademy
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/arcademy
    username: root
    password:
server:
  port: 8081
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
  api-docs:
    path: "/api-docs"